# Generated by Django 4.2.5 on 2023-10-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_offer',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
    ]
