# Generated by Django 4.2.5 on 2023-10-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_product_product_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_offer',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
