# Generated by Django 4.2.5 on 2023-10-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_category_category_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_offer',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
